"""SummarizerSkill — generated by `lottie create skill summarizer`."""
from __future__ import annotations
from lottie.core import BaseSkill
from .schema import SummarizerSkillInput, SummarizerSkillOutput


class SummarizerSkill(BaseSkill[SummarizerSkillInput, SummarizerSkillOutput]):
    """Deterministic skill. Replace `_execute` with real logic."""

    def _execute(self, data: SummarizerSkillInput) -> SummarizerSkillOutput:
        return SummarizerSkillOutput(result=data.text)
