"""ReviewerAgent — generated by `lottie create agent reviewer`."""
from __future__ import annotations
from lottie.core import BaseAgent
from lottie.llm import Message
from .prompts import SYSTEM_PROMPT
from .schema import ReviewerAgentInput, ReviewerAgentOutput


class ReviewerAgent(BaseAgent[ReviewerAgentInput, ReviewerAgentOutput]):
    """LLM-backed agent. Replace `_execute` with real reasoning."""

    def _execute(self, data: ReviewerAgentInput) -> ReviewerAgentOutput:
        response = self.complete(
            [
                Message(role="system", content=SYSTEM_PROMPT),
                Message(role="user", content=data.query),
            ]
        )
        return ReviewerAgentOutput(result=response.content)
