"""DigestAgent — generated by `lottie create agent digest`."""
from __future__ import annotations
from collections.abc import Iterator
from lottie.core import BaseAgent
from lottie.llm import Message
from .prompts import SYSTEM_PROMPT
from .schema import DigestAgentInput, DigestAgentOutput


class DigestAgent(BaseAgent[DigestAgentInput, DigestAgentOutput]):
    """LLM-backed agent. Replace `_execute` with real reasoning."""

    def _execute(self, data: DigestAgentInput) -> DigestAgentOutput:
        if not data.query.strip():
            raise ValueError("query cannot be empty")
        response = self.complete(
            [
                Message(role="system", content=SYSTEM_PROMPT),
                Message(role="user", content=data.query),
            ]
        )
        return DigestAgentOutput(result=response.content)

    def _stream(self, data: DigestAgentInput) -> Iterator[str]:
        """Opt into real token streaming (Round 14): same prompt as _execute, streamed.

        Governance (policy/cost/audit) is inherited via BaseAgent.run_stream; the transport
        wraps these deltas in the StreamingSecretGate before any byte reaches the client."""
        if not data.query.strip():
            raise ValueError("query cannot be empty")
        yield from self.stream_complete(
            [
                Message(role="system", content=SYSTEM_PROMPT),
                Message(role="user", content=data.query),
            ]
        )
