"""DigestAgent — generated by `lottie create agent digest`."""
from __future__ import annotations
from lottie.core import BaseAgent
from lottie.llm import Message
from .prompts import SYSTEM_PROMPT
from .schema import DigestAgentInput, DigestAgentOutput


class DigestAgent(BaseAgent[DigestAgentInput, DigestAgentOutput]):
    """LLM-backed agent. Replace `_execute` with real reasoning."""

    def _execute(self, data: DigestAgentInput) -> DigestAgentOutput:
        response = self.complete(
            [
                Message(role="system", content=SYSTEM_PROMPT),
                Message(role="user", content=data.query),
            ]
        )
        return DigestAgentOutput(result=response.content)
